### ISSUE TITLE
[Feature request] Decomposing concave meshes into convex automatically

### ISSUE THREAD

**Issue by motorsep** [c-d-a/io_export_qmap#11]
Would it be possible to add functionality that would break up marked/selected concave meshes into convex ones (if not on export, maybe as a pre-export function, initiated with a button in the UI or something) ?

**Comment by c-d-a** [comment]
I'm [on record](https://github.com/c-d-a/io_export_qmap/issues/6#issuecomment-1229494212) saying that it's beyond the scope. Seems like the [V-HACD addon](https://github.com/andyp123/blender_vhacd) is no longer maintained, but take a look at it anyway, the sheer amount of options should make it clear that doing this "properly" isn't trivial.
It's not that hard to brute-force though, except doing this stuff in python gets slow fast. Here's a quick attempt, you can run it on the active mesh with "play" button: [convex_decomposition.zip](https://github.com/c-d-a/io_export_qmap/files/10475571/convex_decomposition.zip)
Not sure if I'll add this to the exporter, but I'll leave the issue open for now.

**Comment by motorsep** [comment]
Thanks a bunch! I'll give it a spin.

**Comment by c-d-a** [comment]
Fixed the brute-force version a bit (doesn't split up a basic cube anymore). Here it is in addon form: [object_convex_decomp.zip](https://github.com/c-d-a/io_export_qmap/files/10481105/object_convex_decomp.zip)
I've decided against adding it as a part of the exporter, will instead make a separate repo at some later date. Feel free to report issues here until then.
