### ISSUE TITLE
how to export map with texture

### ISSUE THREAD

**Issue by waradm** [c-d-a/io_export_qmap#17]
i need to know how do this

**Comment by creed59** [comment]
If you're meaning having the image names be the actual file texture name, go into the python script file and do the following to it (for the latest version of the file uploaded on here):
Delete line 432 entirely and 2 lines before, the line just before the break statement, add this to it and you should be good to go: 
texstring = node.image.name.replace(" ","_").
Note: you might want to add another replace method call that replaces the file extension with nothing like this:
.replace(".tga","") or .replace(".dds","").
WARNING: You must be in Viewport Shading: Material Preview Mode for this to work.
