### ISSUE TITLE
Missing paragraph at the end of valve 220 format

### ISSUE THREAD

**Issue by ToTac** [c-d-a/io_export_qmap#5]
Hey there.
When exporting to the Valve 220 format there needs to be one extra newline/paragraph at the end of the file, or else Hammer Editor won't be able to open the generated map file. Other editors might be immune to this issue, however Hammer is not.
It's an easy fix at line 354 I think.

Anyway, thanks for the good work with this addon!

**Comment by c-d-a** [comment]
Fixed in https://github.com/c-d-a/io_export_qmap/commit/8c6b79d7d57e4b0991c5918f478c93b83e33bcfc
Thanks for the report and sorry for the delay.
