### ISSUE TITLE
Mesh option per object ?

### ISSUE THREAD

**Issue by motorsep** [c-d-a/io_export_qmap#8]
Would it be possible to add functionality to export into .map where individual meshes export according to mesh option set via custom properties on that mesh and with meshes that have no custom property set to be exported according to mesh option selected in the add-on's UI ?

This would allow for a lot greater flexibility when making complex maps (as some objects/meshes might require specific mesh option).

**Comment by c-d-a** [comment]
A sound suggestion, but I'll have to think how to implement it. Custom properties are unwieldy, can't even copy them from active to selected objects. On the other hand, I'd like to avoid polluting the blender file with custom object data and extra panels.

**Comment by motorsep** [comment]
Alternatively, you could use Attributes, like so (I don't know if you could, but just an idea):
![image](https://user-images.githubusercontent.com/1927918/211721558-d0da13d2-5983-4f26-93db-56ebe20e2579.png)

And maybe add a floating panel UI to assign attribute from a drop-down selector (or just set of buttons like in the UI of the add-on currently) as typing it would be unwieldy for every mesh in the scene (hopefully attributes can be assigned to multiple selected objects).

**Comment by c-d-a** [comment]
Logically, this is a per-object setting rather than per-mesh, so it has to be something on the Object Properties tab (the orange one). Ideally I'd just re-use some tickbox that has the least chance of interfering with the user's scene, maybe "Texture Space" or something. That's totally unintuitive though, obviously. Anyway, I'll think about it.

**Comment by c-d-a** [comment]
Added in https://github.com/c-d-a/io_export_qmap/commit/671c32fd302da8767193137fa3a6ae9b8397feb3
![override](https://user-images.githubusercontent.com/55441216/211971561-5165d0c6-4be9-40b8-8399-6469145c7664.png)
Ended up adding both a custom property and a custom panel. Might make them toggleable in the preferences at some later point.
